#How to label a Node
#kubectl label nodes <your-node-name> <YOUR-KEY>=<YOUR-VALUE> 
#reference:- https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/ 


#NodeSelector YAML file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-selector
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
      nodeSelector:
        key: value

