#How to Taint a NODE
#kubectl taint node <NODE-NAMR> <KEY>=<VALUE>:<EFFECT>

#Taint-toleration file 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taint-and-toleration
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        env: test
    spec:
      containers:
      - name: nginx
        image: nginx
      tolerations:
      - key: "KEY"
        effect: "EFFECT"
        value: "VALUE"

