apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template: #POD configuration are start from here
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: httpd-container
        image: httpd
        ports:
        - containerPort: 80
