apiVersion: v1
kind: Service
metadata:
  name: replicaset-nodeport-service
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80            
      targetPort: 80      
      nodePort: 30000     # NodePort range 30000 TO 32767
